version: '3.8'

services:

# MySQL container to store users' credentials
#  mysql:
#    image: mysql:8
#    container_name: mysql-container
    # restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_DATABASE: giftgalaxydb
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - app-network


  auth-service:
    image: authentication-service:latest
    container_name: auth-service
    build:
      context: ./authenticationservice
    ports:
      - "8080:8080"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/giftgalaxydb
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: mysql

      #FreeSQLDatabase
      SPRING_DATASOURCE_URL: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7730799
      SPRING_DATASOURCE_USERNAME: sql7730799
      SPRING_DATASOURCE_PASSWORD: UZipIRjYkW
      
    #depends_on:
    #  - mysql
    networks:
      - app-network

  frontend:
    image: frontend-app:latest
    container_name: frontend
    build:
      context: ./frontend/login-signup
    ports:
      - "3000:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

#volumes:
#  mysql-data: